# =============================================================
#  pg_hba.conf — Control de Acceso a PostgreSQL (Primario)
#  Define quién puede conectarse y cómo se autentica
# =============================================================

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Conexiones locales (dentro del contenedor)
local   all             all                                     trust

# Conexiones desde la red interna de Docker (APIs del Servidor 1 y 2)
host    all             all             0.0.0.0/0               md5

# Replicación streaming — solo el usuario replicador puede conectarse
host    replication     replicador      0.0.0.0/0               md5
