#  SERVIDOR 2 — SERVIDOR REPLICA SERVIDOR 1
#  firewall: Contenedor 1 (Nginx Reverse Proxy)
#  frontend-unificado: Contenedor 2 (React App)
#  backend-pagos: Contenedor 3 (Node API Pagos/Tickets)
#  backend-ficha-medica: Contenedor 5 (Node API Ficha Médica)

networks:
  red_app:
    driver: bridge
  red_datos:
    external: true
    name: servidor-3-datos_red_datos

services:

  #  contenedor 1 — Firewall (Proxy Inverso Nginx)
  firewall:
    image: nginx:alpine
    container_name: c1_firewall_s2
    restart: unless-stopped
    ports:
      - "8082:80" # Expuesto para acceso de usuarios
    volumes:
      - ./firewall/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - red_app
    depends_on:
      - frontend-unificado
      - backend-pagos
      - backend-ficha-medica
      - backend-laboratorio

  #  Contenedor 2 — Frontend Unificado (React/Vite)
  frontend-unificado:
    build:
      context: ./frontend-unificado
      dockerfile: Dockerfile
    container_name: c2_frontend_unificado_s2
    restart: unless-stopped
    ports:
      - "5174:5173"
    networks:
      - red_app

  #  Contenedor 3 — Backend Módulo Pagos y Tickets
  backend-pagos:
    build:
      context: ./backend-pagos
      dockerfile: Dockerfile
    container_name: c3_backend_pagos_s2
    restart: unless-stopped
    ports:
      - "3003:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://admin_salud:SaludSegura2025!@haproxy:5432/db_pagos_atencion
    networks:
      - red_app
      - red_datos

  #  Contenedor 5 — Backend Ficha Médica
  backend-ficha-medica:
    build:
      context: ./backend-ficha-medica
      dockerfile: Dockerfile
    container_name: c5_backend_ficha_medica_s2
    restart: unless-stopped
    ports:
      - "3004:3002"
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://admin_salud:SaludSegura2025!@haproxy:5432/db_medico
    networks:
      - red_app
      - red_datos

  #  Contenedor 6 — Backend Laboratorio
  backend-laboratorio:
    build:
      context: ./backend-laboratorio
      dockerfile: Dockerfile
    container_name: c6_backend_laboratorio_s2
    restart: unless-stopped
    ports:
      - "3006:3003"
    environment:
      - PORT=3003
      - DATABASE_URL=postgresql://admin_salud:SaludSegura2025!@haproxy:5432/db_laboratorio
    networks:
      - red_app
      - red_datos
