version: '3.8'

services:
  global-load-balancer:
    image: nginx:alpine
    container_name: global_load_balancer
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
