version: "3.9"

#  SERVIDOR 3 — CAPA DE DATOS CENTRALIZADA
#  postgres-primary: BD principal (lectura/escritura)
#  postgres-replica: BD réplica en hot-standby (solo lectura)

#  Para ejecutar correr el comando
#  docker-compose up -d

networks:
  red_datos:
    driver: bridge

volumes:
  pgdata_primary:
  pgdata_replica:

services:

  #  Base de Datos Principal
  #  Aloja dos bases de datos lógicas:
  #  db_pagos_atencion (módulo Pagos y Tickets)
  #  db_medico (módulo Ficha Médica)
  postgres-primary:
    build:
      context: ./postgres-primary
      dockerfile: Dockerfile
    container_name: c11_postgres_primary
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin_salud
      POSTGRES_PASSWORD: SaludSegura2025!
      POSTGRES_DB: db_pagos_atencion
      REPLICATION_USER: replicador
      REPLICATION_PASSWORD: ReplPass2025!
    ports:
      - "15432:5432"
    volumes:
      - pgdata_primary:/var/lib/postgresql/data
      - ./postgres-primary/init:/docker-entrypoint-initdb.d
    networks:
      - red_datos
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin_salud -d db_pagos_atencion" ]
      interval: 10s
      timeout: 5s
      retries: 5

  #  Base de Datos Réplica (Solo Lectura)
  #  Se sincroniza automáticamente con postgres-primary
  #  mediante Streaming Replication de PostgreSQL.
  postgres-replica:
    build:
      context: ./postgres-replica
      dockerfile: Dockerfile
    container_name: c12_postgres_replica
    restart: unless-stopped
    environment:
      PGUSER: replicador
      PGPASSWORD: ReplPass2025!
      PRIMARY_HOST: postgres-primary
      PRIMARY_PORT: 5432
      REPLICATION_USER: replicador
      REPLICATION_PASSWORD: ReplPass2025!
    ports:
      - "5434:5432"
    volumes:
      - pgdata_replica:/var/lib/postgresql/data
    networks:
      - red_datos
    depends_on:
      postgres-primary:
        condition: service_healthy
